Repository mucsci-students/2022sp-420-NotJava, pull requests merged in 2022-02, with the labels that each got.

#71 Project refactoring
  UMLEditor/UMLEditor.NetCore/Program.cs
  UMLEditor/UMLEditor/Classes/AttributeObject.cs
  UMLEditor/UMLEditor/Classes/Class.cs
  UMLEditor/UMLEditor/Classes/Diagram.cs
  UMLEditor/UMLEditor/Classes/JSONDiagramFile.cs
  UMLEditor/UMLEditor/Classes/Relationship.cs
  UMLEditor/UMLEditor/Exceptions/CustomExceptions.cs
  UMLEditor/UMLEditor/Interfaces/IDiagramFile.cs
  UMLEditor/UMLEditor/Testing/AttributeTester.cs
  UMLEditor/UMLEditor/Testing/ClassTester.cs
  UMLEditor/UMLEditor/Testing/RelationshipTester.cs
  UMLEditor/UMLEditor/Testing/TestingSled.cs
  UMLEditor/UMLEditor/Views/MainWindow.axaml
  UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Labels: bug, Cleanup

#110 fixed #109
  UMLEditor/UMLEditor.NetCore/Program.cs
  UMLEditor/UMLEditor/Views/CommandLine.cs
Labels: bug

#118 Wording & Error Handling Fixes
  UMLEditor/UMLEditor/Classes/AttributeObject.cs
  UMLEditor/UMLEditor/Classes/Class.cs
  UMLEditor/UMLEditor/Views/MainWindow.axaml
  UMLEditor/UMLEditor/Views/MainWindow.axaml.cs
Labels: bug

#120 Documentation Pass For 'experimental-modal-dialogs'
  UMLEditor/UMLEditor/Views/AlertPanel.axaml.cs
  UMLEditor/UMLEditor/Views/ModalDialog.axaml.cs
Labels: documentation
